### ISSUE TITLE
Use httptest.NewRequest

### ISSUE THREAD

**Issue by oliverpool** [techschool/simplebank#12]
Thanks for the great tutorial!

You currently use `http.NewRequest` in your tests:
```go
request, err := http.NewRequest(...)
require.NoError(t, err)
```

This could be replaced with [`httptest.NewRequest`](https://golang.org/pkg/net/http/httptest/#NewRequest) which panics on error
```go
request := httptest.NewRequest(...)
```

**Comment by techschool** [comment]
Good idea. Thank you!
