### ISSUE TITLE
Processing time zone

### ISSUE THREAD

**Issue by topazur** [techschool/simplebank#50]
1. Data obtained through PGSQL contains time fields that carry time zones
2. Use gin.H to return the response
> I get '2022-07-06T10:12:50.672517539Z', but I want '2022-07-06 10:12:50'

**_How to implement formatting in a generic way？_**

**Comment by techschool** [comment]
Hi topazur,
You can use the Format function to convert a timestamp into a string, here's some examples: 
https://gobyexample.com/time-formatting-parsing
But in my opinion, you should keep the timezone and let the client deal with the formatting by itself. The sever should provide full information.

**Comment by topazur** [comment]
Well, that's what I'm doing now, and maybe I haven't found the benefit of doing that yet.
Thank you for your lessons. 
They helped me a lot.
