### ISSUE TITLE
How can i execute raw sql query ? Can we create table using sqlc ? 

### ISSUE THREAD

**Issue by SirJager** [techschool/simplebank#53]
How can i execute raw sql query ? Can we create table using sqlc ? 
I want to create a table dynamically through api . 

Is there any way i can execute raw sql query with this series setup ?

**Comment by techschool** [comment]
Hi,
I think you can run any raw SQL query. You can try it with SQLC to see if it's working or not.
Even if it's not working, you can still create your own `.go` file and write your own Golang code that executes the raw SQL query. (SQLC just helps us write the codes automatically. we can always write the codes on our own if we want).
