### ISSUE TITLE
Race detected when testing in parallel

### ISSUE THREAD

**Issue by boh5** [techschool/simplebank#61]
First of all thanks for the excellent lecture!

I have already learned the [Lecture #24](https://www.youtube.com/watch?v=VcFnqQarpjI&list=PLy_6D98if3ULEtXtNSY_2qN21VCKgoQAE&index=24), and the commit is e2443c3eefeae7735f7b9773c63e9ec8b382883a

I like to run tests in parallel, because it can detect race conditions. So I added `t.Parallel()` in all test functions and inside `t.Run()`.
Then I run `go test -race ./...`, race detected, sample output like that:

```
=== CONT  TestGetAccountAPI/UnauthorizedUser
    testing.go:1319: race detected during execution of test
[GIN] 2022/09/15 - 11:32:26 | 500 |       532.9µs |                 | GET      "/accounts/972"
[GIN] 2022/09/15 - 11:32:26 | 404 |            0s |                 | GET      "/accounts/972"
    --- FAIL: TestGetAccountAPI/UnauthorizedUser (0.01s)

=== RUN   TestGetAccountAPI/NoAuthorization
=== PAUSE TestGetAccountAPI/NoAuthorization
=== CONT  TestGetAccountAPI/NoAuthorization
  github.com/techschool/simplebank/api.newTestServer()
      D:/Files/codes/clone/simplebank/api/main_test.go:20 +0xdb
  github.com/techschool/simplebank/api.TestGetAccountAPI.func19()
      D:/Files/codes/clone/simplebank/api/account_test.go:144 +0x40e
  testing.tRunner()
      E:/Programs/for_coding/Go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      E:/Programs/for_coding/Go/src/testing/testing.go:1493 +0x47

Previous write at 0x00c0001d5668 by goroutine 43:
  github.com/go-playground/validator/v10.(*Validate).registerValidation()
      D:/Files/codes/gopath/pkg/mod/github.com/go-playground/validator/v10@v10.4.1/validator_instance.go:189 +0x116
  github.com/go-playground/validator/v10.(*Validate).RegisterValidationCtx()
      D:/Files/codes/gopath/pkg/mod/github.com/go-playground/validator/v10@v10.4.1/validator_instance.go:173 +0xa4
  github.com/go-playground/validator/v10.(*Validate).RegisterValidation()
      D:/Files/codes/gopath/pkg/mod/github.com/go-playground/validator/v10@v10.4.1/validator_instance.go:163 +0x46
  github.com/techschool/simplebank/api.NewServer()
      D:/Files/codes/clone/simplebank/api/server.go:36 +0x2e9
  github.com/techschool/simplebank/api.newTestServer()
      D:/Files/codes/clone/simplebank/api/main_test.go:20 +0xdb
  github.com/techschool/simplebank/api.TestGetAccountAPI.func19()
      D:/Files/codes/clone/simplebank/api/account_test.go:144 +0x40e
  testing.tRunner()
      E:/Programs/for_coding/Go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      E:/Programs/for_coding/Go/src/testing/testing.go:1493 +0x47
```

Then I found `v.RegisterValidation("currency", validCurrency)` is not thead-safe, so I added a mutex in `NewServer()` function, but it still not working, a sample output like that:

```
=== CONT  TestGetAccountAPI
    testing.go:1319: race detected during execution of test
--- FAIL: TestGetAccountAPI (0.42s)
=== RUN   TestGetAccountAPI/OK
=== PAUSE TestGetAccountAPI/OK
=== CONT  TestGetAccountAPI/OK
  github.com/gin-gonic/gin.(*Context).Next()
      D:/Files/codes/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x14a
  github.com/gin-gonic/gin.RecoveryWithWriter.func1()
      D:/Files/codes/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 +0xae
  github.com/gin-gonic/gin.(*Context).Next()
      D:/Files/codes/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x219
  github.com/gin-gonic/gin.LoggerWithConfig.func1()
      D:/Files/codes/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0x189
  github.com/gin-gonic/gin.(*Context).Next()
      D:/Files/codes/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0xb63
  github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()
      D:/Files/codes/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x75b
  github.com/gin-gonic/gin.(*Engine).ServeHTTP()
      D:/Files/codes/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x367
  github.com/techschool/simplebank/api.TestCreateAccountAPI.func13()
      D:/Files/codes/clone/simplebank/api/account_test.go:273 +0x771
  testing.tRunner()
      E:/Programs/for_coding/Go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      E:/Programs/for_coding/Go/src/testing/testing.go:1493 +0x47

Previous write at 0x00c0004140a8 by goroutine 62:
  github.com/go-playground/validator/v10.(*Validate).registerValidation()
      D:/Files/codes/gopath/pkg/mod/github.com/go-playground/validator/v10@v10.4.1/validator_instance.go:189 +0x116
  github.com/go-playground/validator/v10.(*Validate).RegisterValidationCtx()
      D:/Files/codes/gopath/pkg/mod/github.com/go-playground/validator/v10@v10.4.1/validator_instance.go:173 +0xa4
  github.com/go-playground/validator/v10.(*Validate).RegisterValidation()
      D:/Files/codes/gopath/pkg/mod/github.com/go-playground/validator/v10@v10.4.1/validator_instance.go:163 +0x46
    --- PASS: TestGetAccountAPI/OK (0.03s)
```

It seems that `ctx.Next()` in `AuthMiddleware` cause the error, so I locked the `ctx.Next()`, but the error still exists.

After several debugging, I found that if I delete `t.Parallel()` in `user_test.go` the error gone.

But the problem still not fixed, and I don't known why.

Could you please help me with that problem?  The error is easy to reproduce, just make all tests run in parallel and run `go test -race ./...`.

Thanks.

**Comment by techschool** [comment]
Hey Huangbo,
The race issue is indeed caused by the validator engine being called multiple times by the parallel test cases (when they create a new server).
So the solution is to just move it out of the NewServer() function, and put it inside the special init() function:
```
func init() {
	if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
		v.RegisterValidation("currency", validCurrency)
	}
}

// NewServer creates a new HTTP server and set up routing.
func NewServer(config util.Config, store db.Store) (*Server, error) {
	tokenMaker, err := token.NewPasetoMaker(config.TokenSymmetricKey)
	if err != nil {
		return nil, fmt.Errorf("cannot create token maker: %w", err)
	}

	server := &Server{
		config:     config,
		store:      store,
		tokenMaker: tokenMaker,
	}

	server.setupRouter()
	return server, nil
}
```

**Comment by boh5** [comment]
@techschool Thanks for your reply, your solution do save me!

I understand now that register validator in `init()` function make sure `RegisterValidation` called only once.

But I'm still confused why the `sync.Mutex` not working. 
According to the `RegisterValidation` doc, it say "if the key already exists, the previous validation function will be replaced.", I think it should works well, even if it's inefficient. Am I use the mutex in a wrong way?

Here the way I use mutex:
```go
var mutex sync.Mutex

// NewServer creates a new HTTP server and setup routing
func NewServer(config util.Config, store db.Store) (*Server, error) {
	tokenMaker, err := token.NewPasetoMaker(config.TokenSymmetricKey)
	if err != nil {
		return nil, fmt.Errorf("cannot create token make: %w", err)
	}
	server := &Server{
		config:     config,
		store:      store,
		tokenMaker: tokenMaker,
	}
	
	mutex.Lock()
	if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
		err := v.RegisterValidation("currency", validCurrency)
		if err != nil {
			log.Fatal("register validation err:", err)
		}
	}
	mutex.Unlock()
	
	server.setupRouter()

	return server, nil
}
```

Sorry to bother again.

**Comment by frogfromlake** [comment]
> @techschool Thanks for your reply, your solution do save me!
> 
> I understand now that register validator in `init()` function make sure `RegisterValidation` called only once.
> 
> But I'm still confused why the `sync.Mutex` not working. According to the `RegisterValidation` doc, it say "if the key already exists, the previous validation function will be replaced.", I think it should works well, even if it's inefficient. Am I use the mutex in a wrong way?
> 
> Here the way I use mutex:
> 
> ```go
> var mutex sync.Mutex
> 
> // NewServer creates a new HTTP server and setup routing
> func NewServer(config util.Config, store db.Store) (*Server, error) {
> 	tokenMaker, err := token.NewPasetoMaker(config.TokenSymmetricKey)
> 	if err != nil {
> 		return nil, fmt.Errorf("cannot create token make: %w", err)
> 	}
> 	server := &Server{
> 		config:     config,
> 		store:      store,
> 		tokenMaker: tokenMaker,
> 	}
> 	
> 	mutex.Lock()
> 	if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
> 		err := v.RegisterValidation("currency", validCurrency)
> 		if err != nil {
> 			log.Fatal("register validation err:", err)
> 		}
> 	}
> 	mutex.Unlock()
> 	
> 	server.setupRouter()
> 
> 	return server, nil
> }
> ```
> 
> Sorry to bother again.

The mutexes are not working because each test runs in its own goroutine when you use t.Parallel().
Each test gets its own instance of the mutex, so the mutex doesn't prevent the concurrent execution of the tests which leads to race conditions where multiple tests try to acquire the lock at the same time.
so even if you declare a mutex outside the function, each test will have its own instance of the mutex. Quang's solution is the way to go i guess.
