### ISSUE TITLE
Unit Test for SQLC is broken

### ISSUE THREAD

**Issue by adiatma85** [techschool/simplebank#81]
Hello, firstly I would say thank you for the great tutorial in youtube.

I stumbled upon a problem where when I run ``make test``, it return error like this:
![image](https://user-images.githubusercontent.com/57523711/218117502-a567aa09-37be-40b6-913c-0b164adb2d83.png)

The problem are, when we executing the command for ``make test``, the test skipped ``func TestMain`` so the database connection doesn't created hence, this happen.

Temporary solution is, well, make new sql connection for each function. But as I read from ``github.com/stretchr/testify/suite``, TestMain could be replaced by this.

**Comment by techschool** [comment]
It looks more like you haven't run the db migration, so the table "users" doesn't exist yet.
